<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon as Carbon;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //insert default records
        DB::table('countries')->insert(array(
            array('id' => 'AD', 'country_name_en' => 'Andorra', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AE', 'country_name_en' => 'United Arab Emirates', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AF', 'country_name_en' => 'Afghanistan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AG', 'country_name_en' => 'Antigua and Barbuda', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AI', 'country_name_en' => 'Anguilla', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AL', 'country_name_en' => 'Albania', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AM', 'country_name_en' => 'Armenia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AN', 'country_name_en' => 'Netherlands Antilles', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AO', 'country_name_en' => 'Angola', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AQ', 'country_name_en' => 'Antarctica', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AR', 'country_name_en' => 'Argentina', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AS', 'country_name_en' => 'American Samoa', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AT', 'country_name_en' => 'Austria', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AU', 'country_name_en' => 'Australia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AW', 'country_name_en' => 'Aruba', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AX', 'country_name_en' => 'Aland Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'AZ', 'country_name_en' => 'Azerbaijan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BA', 'country_name_en' => 'Bosnia and Herzegovina', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BB', 'country_name_en' => 'Barbados', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BD', 'country_name_en' => 'Bangladesh', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BE', 'country_name_en' => 'Belgium', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BF', 'country_name_en' => 'Burkina Faso', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BG', 'country_name_en' => 'Bulgaria', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BH', 'country_name_en' => 'Bahrain', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BI', 'country_name_en' => 'Burundi', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BJ', 'country_name_en' => 'Benin', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BL', 'country_name_en' => 'Saint BarthÃ©lemy', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BM', 'country_name_en' => 'Bermuda', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BN', 'country_name_en' => 'Brunei', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BO', 'country_name_en' => 'Bolivia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BQ', 'country_name_en' => 'Bonaire, Saint Eustatius and Saba ', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BR', 'country_name_en' => 'Brazil', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BS', 'country_name_en' => 'Bahamas', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BT', 'country_name_en' => 'Bhutan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BV', 'country_name_en' => 'Bouvet Island', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BW', 'country_name_en' => 'Botswana', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BY', 'country_name_en' => 'Belarus', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'BZ', 'country_name_en' => 'Belize', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CA', 'country_name_en' => 'Canada', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CC', 'country_name_en' => 'Cocos Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CD', 'country_name_en' => 'Democratic Republic of the Congo', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CF', 'country_name_en' => 'Central African Republic', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CG', 'country_name_en' => 'Republic of the Congo', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CH', 'country_name_en' => 'Switzerland', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CI', 'country_name_en' => 'Ivory Coast', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CK', 'country_name_en' => 'Cook Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CL', 'country_name_en' => 'Chile', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CM', 'country_name_en' => 'Cameroon', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CN', 'country_name_en' => 'China', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CO', 'country_name_en' => 'Colombia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CR', 'country_name_en' => 'Costa Rica', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CU', 'country_name_en' => 'Cuba', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CV', 'country_name_en' => 'Cape Verde', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CW', 'country_name_en' => 'Curaçao', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CX', 'country_name_en' => 'Christmas Island', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CY', 'country_name_en' => 'Cyprus', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'CZ', 'country_name_en' => 'Czech Republic', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'DE', 'country_name_en' => 'Germany', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'DJ', 'country_name_en' => 'Djibouti', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'DK', 'country_name_en' => 'Denmark', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'DM', 'country_name_en' => 'Dominica', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'DO', 'country_name_en' => 'Dominican Republic', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'DZ', 'country_name_en' => 'Algeria', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'EC', 'country_name_en' => 'Ecuador', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'EE', 'country_name_en' => 'Estonia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'EG', 'country_name_en' => 'Egypt', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'EH', 'country_name_en' => 'Western Sahara', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ER', 'country_name_en' => 'Eritrea', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ES', 'country_name_en' => 'Spain', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ET', 'country_name_en' => 'Ethiopia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'FI', 'country_name_en' => 'Finland', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'FJ', 'country_name_en' => 'Fiji', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'FK', 'country_name_en' => 'Falkland Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'FM', 'country_name_en' => 'Micronesia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'FO', 'country_name_en' => 'Faroe Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'FR', 'country_name_en' => 'France', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GA', 'country_name_en' => 'Gabon', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GB', 'country_name_en' => 'United Kingdom', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GD', 'country_name_en' => 'Grenada', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GE', 'country_name_en' => 'Georgia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GF', 'country_name_en' => 'French Guiana', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GG', 'country_name_en' => 'Guernsey', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GH', 'country_name_en' => 'Ghana', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GI', 'country_name_en' => 'Gibraltar', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GL', 'country_name_en' => 'Greenland', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GM', 'country_name_en' => 'Gambia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GN', 'country_name_en' => 'Guinea', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GP', 'country_name_en' => 'Guadeloupe', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GQ', 'country_name_en' => 'Equatorial Guinea', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GR', 'country_name_en' => 'Greece', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GS', 'country_name_en' => 'South Georgia and the South Sandwich Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GT', 'country_name_en' => 'Guatemala', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GU', 'country_name_en' => 'Guam', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GW', 'country_name_en' => 'Guinea-Bissau', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'GY', 'country_name_en' => 'Guyana', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'HK', 'country_name_en' => 'Hong Kong', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'HM', 'country_name_en' => 'Heard Island and McDonald Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'HN', 'country_name_en' => 'Honduras', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'HR', 'country_name_en' => 'Croatia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'HT', 'country_name_en' => 'Haiti', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'HU', 'country_name_en' => 'Hungary', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ID', 'country_name_en' => 'Indonesia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IE', 'country_name_en' => 'Ireland', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IL', 'country_name_en' => 'Israel', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IM', 'country_name_en' => 'Isle of Man', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IN', 'country_name_en' => 'India', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IO', 'country_name_en' => 'British Indian Ocean Territory', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IQ', 'country_name_en' => 'Iraq', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IR', 'country_name_en' => 'Iran', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IS', 'country_name_en' => 'Iceland', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'IT', 'country_name_en' => 'Italy', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'JE', 'country_name_en' => 'Jersey', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'JM', 'country_name_en' => 'Jamaica', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'JO', 'country_name_en' => 'Jordan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'JP', 'country_name_en' => 'Japan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KE', 'country_name_en' => 'Kenya', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KG', 'country_name_en' => 'Kyrgyzstan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KH', 'country_name_en' => 'Cambodia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KI', 'country_name_en' => 'Kiribati', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KM', 'country_name_en' => 'Comoros', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KN', 'country_name_en' => 'Saint Kitts and Nevis', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KP', 'country_name_en' => 'North Korea', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KR', 'country_name_en' => 'South Korea', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KW', 'country_name_en' => 'Kuwait', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KY', 'country_name_en' => 'Cayman Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'KZ', 'country_name_en' => 'Kazakhstan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LA', 'country_name_en' => 'Laos', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LB', 'country_name_en' => 'Lebanon', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LC', 'country_name_en' => 'Saint Lucia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LI', 'country_name_en' => 'Liechtenstein', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LK', 'country_name_en' => 'Sri Lanka', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LR', 'country_name_en' => 'Liberia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LS', 'country_name_en' => 'Lesotho', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LT', 'country_name_en' => 'Lithuania', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LU', 'country_name_en' => 'Luxembourg', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LV', 'country_name_en' => 'Latvia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'LY', 'country_name_en' => 'Libya', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MA', 'country_name_en' => 'Morocco', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MC', 'country_name_en' => 'Monaco', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MD', 'country_name_en' => 'Moldova', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ME', 'country_name_en' => 'Montenegro', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MF', 'country_name_en' => 'Saint Martin', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MG', 'country_name_en' => 'Madagascar', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MH', 'country_name_en' => 'Marshall Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MK', 'country_name_en' => 'Macedonia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ML', 'country_name_en' => 'Mali', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MM', 'country_name_en' => 'Myanmar', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MN', 'country_name_en' => 'Mongolia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MO', 'country_name_en' => 'Macao', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MP', 'country_name_en' => 'Northern Mariana Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MQ', 'country_name_en' => 'Martinique', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MR', 'country_name_en' => 'Mauritania', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MS', 'country_name_en' => 'Montserrat', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MT', 'country_name_en' => 'Malta', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MU', 'country_name_en' => 'Mauritius', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MV', 'country_name_en' => 'Maldives', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MW', 'country_name_en' => 'Malawi', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MX', 'country_name_en' => 'Mexico', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MY', 'country_name_en' => 'Malaysia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'MZ', 'country_name_en' => 'Mozambique', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NA', 'country_name_en' => 'Namibia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NC', 'country_name_en' => 'New Caledonia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NE', 'country_name_en' => 'Niger', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NF', 'country_name_en' => 'Norfolk Island', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NG', 'country_name_en' => 'Nigeria', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NI', 'country_name_en' => 'Nicaragua', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NL', 'country_name_en' => 'Netherlands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NO', 'country_name_en' => 'Norway', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NP', 'country_name_en' => 'Nepal', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NR', 'country_name_en' => 'Nauru', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NU', 'country_name_en' => 'Niue', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'NZ', 'country_name_en' => 'New Zealand', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'OM', 'country_name_en' => 'Oman', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PA', 'country_name_en' => 'Panama', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PE', 'country_name_en' => 'Peru', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PF', 'country_name_en' => 'French Polynesia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PG', 'country_name_en' => 'Papua New Guinea', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PH', 'country_name_en' => 'Philippines', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PK', 'country_name_en' => 'Pakistan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PL', 'country_name_en' => 'Poland', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PM', 'country_name_en' => 'Saint Pierre and Miquelon', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PN', 'country_name_en' => 'Pitcairn', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PR', 'country_name_en' => 'Puerto Rico', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PS', 'country_name_en' => 'Palestinian Territory', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PT', 'country_name_en' => 'Portugal', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PW', 'country_name_en' => 'Palau', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'PY', 'country_name_en' => 'Paraguay', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'QA', 'country_name_en' => 'Qatar', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'RE', 'country_name_en' => 'Reunion', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'RO', 'country_name_en' => 'Romania', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'RS', 'country_name_en' => 'Serbia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'RU', 'country_name_en' => 'Russia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'RW', 'country_name_en' => 'Rwanda', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SA', 'country_name_en' => 'Saudi Arabia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SB', 'country_name_en' => 'Solomon Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SC', 'country_name_en' => 'Seychelles', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SD', 'country_name_en' => 'Sudan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SE', 'country_name_en' => 'Sweden', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SG', 'country_name_en' => 'Singapore', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SH', 'country_name_en' => 'Saint Helena', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SI', 'country_name_en' => 'Slovenia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SJ', 'country_name_en' => 'Svalbard and Jan Mayen', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SK', 'country_name_en' => 'Slovakia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SL', 'country_name_en' => 'Sierra Leone', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SM', 'country_name_en' => 'San Marino', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SN', 'country_name_en' => 'Senegal', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SO', 'country_name_en' => 'Somalia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SR', 'country_name_en' => 'Suriname', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SS', 'country_name_en' => 'South Sudan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ST', 'country_name_en' => 'Sao Tome and Principe', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SV', 'country_name_en' => 'El Salvador', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SX', 'country_name_en' => 'Sint Maarten', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SY', 'country_name_en' => 'Syria', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'SZ', 'country_name_en' => 'Swaziland', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TC', 'country_name_en' => 'Turks and Caicos Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TD', 'country_name_en' => 'Chad', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TF', 'country_name_en' => 'French Southern Territories', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TG', 'country_name_en' => 'Togo', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TH', 'country_name_en' => 'Thailand', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TJ', 'country_name_en' => 'Tajikistan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TK', 'country_name_en' => 'Tokelau', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TL', 'country_name_en' => 'East Timor', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TM', 'country_name_en' => 'Turkmenistan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TN', 'country_name_en' => 'Tunisia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TO', 'country_name_en' => 'Tonga', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TR', 'country_name_en' => 'Turkey', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TT', 'country_name_en' => 'Trinidad and Tobago', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TV', 'country_name_en' => 'Tuvalu', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TW', 'country_name_en' => 'Taiwan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'TZ', 'country_name_en' => 'Tanzania', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'UA', 'country_name_en' => 'Ukraine', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'UG', 'country_name_en' => 'Uganda', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'UM', 'country_name_en' => 'United States Minor Outlying Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'US', 'country_name_en' => 'United States', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'UY', 'country_name_en' => 'Uruguay', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'UZ', 'country_name_en' => 'Uzbekistan', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'VA', 'country_name_en' => 'Vatican', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'VC', 'country_name_en' => 'Saint Vincent and the Grenadines', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'VE', 'country_name_en' => 'Venezuela', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'VG', 'country_name_en' => 'British Virgin Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'VI', 'country_name_en' => 'U.S. Virgin Islands', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'VN', 'country_name_en' => 'Vietnam', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'VU', 'country_name_en' => 'Vanuatu', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'WF', 'country_name_en' => 'Wallis and Futuna', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'WS', 'country_name_en' => 'Samoa', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'YE', 'country_name_en' => 'Yemen', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'YT', 'country_name_en' => 'Mayotte', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ZA', 'country_name_en' => 'South Africa', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ZM', 'country_name_en' => 'Zambia', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),
            array('id' => 'ZW', 'country_name_en' => 'Zimbabwe', 'created_at' => Carbon::Now(), 'updated_at' => Carbon::Now()),

        ));
    }
}
